name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json
      - name: Set up Purescript and Spago
        run: npm i -g purescript spago@next
      - name: Install Node and Spago dependencies
        run: npm i
      - name: Build static website
        run: npm run build
      - name: Upload /dist as artifact for GitHub Pages deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy straight from artifact
        uses: actions/deploy-pages@v4
        id: deployment
        with:
          reporting_interval: 1000
